- name: install xdebug
  shell: pecl install xdebug
  register: xdebug_install_result
  changed_when: "'Build process completed successfully' in xdebug_install_result.stdout"
  failed_when: "'Build process completed successfully' not in xdebug_install_result.stdout and 'pecl/xdebug is already installed' not in xdebug_install_result.stdout"

- name: find location of xdebug.so
  shell: find / -name xdebug.so
  register: xdebug_install_path
  failed_when: "'xdebug.so' not in xdebug_install_path.stdout"

- name: write xdebug.ini
  template: src=xdebug.ini.j2 dest=/etc/php5/conf.d/xdebug.ini
