tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  external_code_coverage:
    timeout: 1200  # timeout in seconds : 20 minutes

filter:
  paths
    - src/*
  excluded_paths:
    - app/*
    - build/*
    - public/*
    - tools/*
    - */Tests/*

checks:
  php:
    code_rating: true
    duplication: true
