build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]

tools:
  external_code_coverage:
    timeout: 600  # timeout in seconds : 10 minutes

filter:
  paths:
    - src/*
  excluded_paths:
    # Psi is a facade class and complexity/coupling does not matter here
    - src/Psi.php
    - app/*
    - tests/*

checks:
  php:
    code_rating: true
    duplication: true
