tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  external_code_coverage:
    timeout: 600  # timeout in seconds : 10 minutes

filter:
  paths:
    - src/*
  excluded_paths:
    - app/*
    - build/*
    - public/*
    - tools/*
    - src/*/Test/*
    - src/*/Tests/*
    - src/*/*/Test/*
    - src/*/*/Tests/*
    - src/*/*/*/Test/*
    - src/*/*/*/Tests/*
    - src/*/*/*/*/Test/*
    - src/*/*/*/*/Tests/*
    - src/*/*/*/*/*/Test/*
    - src/*/*/*/*/*/Tests/*

checks:
  php:
    code_rating: true
    duplication: true
