tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  external_code_coverage: true

filter:
  excluded_paths:
    - app/*
    - build/*
    - public/*
    - tools/*
    - src/*/Tests
    - src/*/*/Tests
    - src/*/*/*/Tests
    - src/*/*/*/*/Tests
    - src/*/*/*/*/*/Tests

checks:
  php:
    code_rating: true
    duplication: true
