language: php
php:
  - 5.5
  - 5.6
#  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader

script:
  - phpunit --coverage-clover=coverage.clover
  - php tools/scrutinizer/ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - karsten.john.gerber@googlemail.com
