language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist
  - composer dumpautoload -o -a

script:
  - phpunit --coverage-clover=coverage.clover
  - php tools/scrutinizer/ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - karsten.john.gerber@googlemail.com
