
- name: ensure latest version of php-fpm is installed
  apt: pkg=php5-fpm state=latest

- name: configure php-fpm memory limit for PHP-FPM
  lineinfile: dest=/etc/php5/fpm/php.ini state=present regexp='memory_limit.*=.*$' line="memory_limit = {{ memory_limit }}"
  notify:
    - restart php-fpm

- name: configure php-fpm memory limit for PHP-CLI
  lineinfile: dest=/etc/php5/cli/php.ini state=present regexp='memory_limit.*=.*$' line="memory_limit = {{ memory_limit }}"
  notify:
    - restart php-fpm

- name: ensure php-fpm is running as correct user and group
  template: src=runAs.j2 dest=/etc/php5/fpm/pool.d/z_www_runAs.conf
  notify:
    - restart php-fpm

- name: ensure php-fpm is running on start up
  service: name=php5-fpm state=started enabled=true
