- name: update apt cache
  apt:  update_cache=yes

#- name: ensure vim is at the latest version
#  apt:  pkg=vim state=latest
#
#- name: ensure htop is at the latest version
#  apt:  pkg=htop state=latest
#
#- name: ensure latest version of curl is installed
#  apt: pkg=curl state=latest


- name: ensure common packages are installed
  apt:  pkg={{ item }} state=latest
  with_items:
    - vim
    - htop
    - curl
    - mc
    - git

- name: ensure ntp is at the latest version
  apt:  pkg=ntp,ntpdate state=latest
  tags: ntp

- name: ensure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: ensure ntp is running and enabled
  service: name=ntp state=started enabled=yes
  tags: ntp

